
name: CD
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: yarn install
      - name: type-check
        run: yarn check
      - name: test
        run: yarn test
  create-release:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: get short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          target_commitish: ${{ github.sha }}
          tag_name: ${{ env.short_sha }}
          name: "Release - ${{ env.short_sha }}"
          draft: true
          prerelease: false
